const {_electron:electron}=require('@playwright/test');const path=require('node:path'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),dest=path.join(root,'test-output/desktop');await fs.mkdir(dest,{recursive:true});const env={...process.env,LIPIDFLOW_TEST_USER_DATA:path.join(dest,'user-'+Date.now())};const app=await electron.launch({...(process.env.LIPIDFLOW_EXECUTABLE?{executablePath:process.env.LIPIDFLOW_EXECUTABLE,args:[]}:{args:[root]}),env});try{
const page=await app.firstWindow();await page.waitForSelector('.lf-workflow-card:not(:disabled)',{timeout:120000});assert.equal(await page.locator('.lf-workflow-card').count(),1);assert.equal(await page.locator('.lf-tool-card').count(),1);assert.equal(await page.title(),'LipidFlow');await page.screenshot({path:path.join(dest,'overview.png')});
const p=await page.evaluate(async parent=>window.desktop.invoke('createProject',{name:'Validation '+Date.now(),mode:'workflow',parent}),dest);
const dirs=(await fs.readdir(path.join(root,'test-output'))).filter(n=>/^engine-/.test(n)).sort();const f=path.join(root,'test-output',dirs.at(-1),'fixtures');
const imported=await page.evaluate(params=>window.desktop.invoke('run',{operation:'import',params}),{source:'tables',sides:['pos'],peaks_pos:path.join(f,'peaks.csv'),annotations_pos:path.join(f,'annotations.csv')});assert.equal(imported.runs.at(-1).status,'completed');
const quantified=await page.evaluate(payload=>window.desktop.invoke('run',payload),{operation:'quantification',params:{isXlsx:path.join(f,'is.xlsx'),isopt_pos:path.join(f,'isopt.csv'),classMapping:JSON.stringify({PC:['PC standard']})},inputId:imported.runs.at(-1).id});assert.equal(quantified.runs.at(-1).status,'completed');
await page.reload();await page.waitForSelector('.lf-workflow-card:not(:disabled)',{timeout:120000});await page.getByRole('button',{name:'Recent projects',exact:true}).click();await page.getByRole('button',{name:new RegExp(p.name)}).click();await page.getByRole('button',{name:'Data import',exact:false}).click();assert.equal(await page.getByLabel('Y_IS_opt · POS',{exact:true}).count(),0);await page.getByLabel('Raw data folder · POS',{exact:true}).waitFor();await page.screenshot({path:path.join(dest,'workflow.png')});assert.equal(await page.locator('.step-list .step').count(),5);
await page.getByRole('button',{name:'Peak picking',exact:false}).first().click();await page.getByText('Advanced peak detection',{exact:true}).click();await page.getByLabel('Prefilter · minimum scans',{exact:true}).fill('4');await page.getByLabel('Minimum m/z difference',{exact:true}).fill('-0.001');await page.getByLabel('Integration method',{exact:true}).selectOption('1');await page.getByText('Diagnostic plots',{exact:true}).click();await page.getByLabel('Group for figures',{exact:true}).fill('QC');assert.equal(await page.getByText('Missing peak filling · Enabled',{exact:false}).count(),1);await page.screenshot({path:path.join(dest,'picking-parameters.png')});
await page.getByRole('button',{name:'Absolute quantification',exact:false}).first().click();await page.getByLabel('Y_IS_opt · POS',{exact:true}).waitFor();await page.getByLabel('Result table').selectOption('POS absolute quantification');await page.waitForFunction(()=>document.querySelector('tbody')?.textContent?.includes('PC(16:0/18:1)'));await page.screenshot({path:path.join(dest,'quantification.png')});
await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByText('Theme',{exact:true}).locator('..').locator('select').selectOption('dark');await page.getByRole('button',{name:'Close dialog'}).click();await page.screenshot({path:path.join(dest,'dark-results.png')});
await page.getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('button',{name:/Internal standard exploration Extract QC/}).click();await page.screenshot({path:path.join(dest,'create-extraction.png')});console.log('Desktop navigation, persisted project, live R quantification and screenshots passed.');
}finally{await app.close()}})().catch(e=>{console.error(e);process.exitCode=1});
