const {resources,exe:runtimeExe}=require('./runtime.cjs');
const root=require('node:path').resolve(__dirname,'..');
const { _electron:electron,expect}=require(root+'/node_modules/@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const {rEnvironment}=require(root+'/electron/platform.cjs');const exe=runtimeExe;
(async()=>{const base=path.join(require('node:os').tmpdir(),'lipidflow-review-'+Date.now());await fs.mkdir(base,{recursive:true});const fixture=path.join(base,'fixture');const r=spawnSync(exe,['--vanilla',root+'/tests/exploration-fixture.R',fixture],{cwd:root,env:rEnvironment(exe),encoding:'utf8'});assert.equal(r.status,0,r.stderr);
const app=await electron.launch({...(process.env.LIPIDFLOW_EXECUTABLE?{executablePath:process.env.LIPIDFLOW_EXECUTABLE,args:[]}:{args:[root]}),env:{...process.env,LIPIDFLOW_TEST_USER_DATA:path.join(base,'user')}});try{const page=await app.firstWindow();await page.waitForSelector('.lf-workflow-card:not(:disabled)',{timeout:120000});const p=await page.evaluate(parent=>window.desktop.invoke('createProject',{name:'Interactive validation',mode:'extraction',parent}),base);
const dir=path.join(p.path,'runs','fixture');await fs.mkdir(dir,{recursive:true});await fs.copyFile(path.join(fixture,'object.rds'),path.join(dir,'object.rds'));p.runs=[{id:'fixture',operation:'extraction',params:{sides:['pos','neg']},status:'completed',started:new Date().toISOString(),result:{kind:'extraction',sides:['pos','neg'],tables:[],capabilities:['tables']}}];await fs.writeFile(path.join(p.path,'project.json'),JSON.stringify(p));await page.evaluate(p=>window.desktop.invoke('openProject',p),p.path);
const seeded=await page.evaluate(()=>window.desktop.invoke('run',{operation:'selection',params:{},inputId:'fixture'}));assert.equal(seeded.runs.at(-1).status,'completed',seeded.runs.at(-1).error);
await page.reload();await page.waitForSelector('.lf-workflow-card:not(:disabled)',{timeout:120000});await page.getByRole('button',{name:'Recent projects',exact:true}).click();await page.getByRole('button',{name:/Interactive validation/}).click();await expect(page.getByLabel('Result polarity')).toBeVisible();await expect(page.getByTestId('eic-trace')).toHaveCount(4);
await page.getByRole('tab',{name:'Final result table',exact:true}).click();const final=page.locator('.lf-is-list, .lf-full-is-table');await final.getByRole('button',{name:'Peak_Area',exact:false}).click();await expect(final.locator('th').filter({hasText:'Peak_Area'})).toHaveAttribute('aria-sort','ascending');await final.getByRole('button',{name:'Peak_Area',exact:false}).click();assert((await final.locator('tbody tr').first().innerText()).includes('IS_002'));
await final.locator('tbody tr[data-is-id="IS_002"]').click();await expect(page.locator('.lf-detail-title')).toContainText('PE standard');await page.locator('.lf-peak-chart').getByRole('checkbox',{name:'+Na',exact:true}).uncheck();await expect(page.getByTestId('eic-trace')).toHaveCount(2);await page.getByRole('checkbox',{name:'Sample.mzXML',exact:true}).uncheck();await expect(page.getByTestId('eic-trace')).toHaveCount(1);await page.locator('.lf-peak-chart').getByRole('checkbox',{name:'+Na',exact:true}).check();await page.getByRole('checkbox',{name:'Sample.mzXML',exact:true}).check();await page.getByRole('checkbox',{name:'Normalize each trace'}).check();
const svg=page.getByRole('img',{name:'Interactive peak shapes'});await svg.scrollIntoViewIfNeeded();const b=await svg.boundingBox();await page.mouse.move(b.x+b.width*.3,b.y+b.height*.5);await expect(page.locator('.lf-peak-readout')).toContainText('QC.mzXML');await page.mouse.down();await page.mouse.move(b.x+b.width*.7,b.y+b.height*.5);await page.mouse.up();await page.getByRole('button',{name:'Reset zoom'}).click();
await page.getByLabel('Adduct to use').selectOption('+Na');await page.getByRole('button',{name:'Confirm adduct',exact:true}).click();await expect(page.locator('.lf-detail-title')).toContainText('Manually confirmed',{timeout:120000});await expect(page.locator('.lf-detail-title')).toContainText('IS_002');
await page.getByLabel('Result polarity').selectOption('neg');await expect(page.locator('.lf-detail-title')).toContainText('Automatic');await final.locator('tbody tr[data-is-id="IS_002"]').click();await page.getByLabel('Adduct to use').selectOption('+Na');await page.getByRole('button',{name:'Confirm adduct',exact:true}).click();await expect(page.locator('.lf-detail-title')).toContainText('Manually confirmed',{timeout:120000});await expect(page.getByLabel('Result polarity')).toHaveValue('neg');
await page.getByLabel('Result polarity').selectOption('pos');await final.locator('tbody tr[data-is-id="IS_002"]').click();await expect(page.locator('.lf-detail-title')).toContainText('Manually confirmed');await final.locator('tbody tr[data-is-id="IS_001"]').click();await page.getByLabel('Adduct to use').selectOption('+Na');await page.getByRole('button',{name:'Confirm adduct',exact:true}).click();await expect(page.locator('.lf-detail-title')).toContainText('Manually confirmed',{timeout:120000});
await page.screenshot({path:base+'/interactive-results.png'});for(const [width,height] of [[1080,700],[1440,900],[2200,950]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[width,height]);await page.waitForTimeout(150);const layout=await page.evaluate(()=>({height:innerHeight,scroll:document.documentElement.scrollHeight,confirm:document.querySelector('.lf-adduct-confirm').getBoundingClientRect().bottom,svg:document.querySelector('.lf-peak-chart svg').getBoundingClientRect().bottom}));assert(layout.scroll<=layout.height+2,JSON.stringify(layout));assert(layout.confirm<layout.height&&layout.svg<=layout.height,JSON.stringify(layout));await page.screenshot({path:base+`/layout-${width}.png`})}await page.getByRole('button',{name:'Inputs & parameters',exact:true}).click();await expect(page.getByLabel('Inputs and parameters')).toBeVisible();await page.getByRole('button',{name:'Close inputs'}).click();await page.getByRole('tab',{name:'Adduct details',exact:true}).click();await expect(page.locator('.lf-candidate-view table')).toBeVisible();await page.getByRole('tab',{name:'Peak shapes',exact:true}).click();let saved=JSON.parse(await fs.readFile(path.join(p.path,'project.json')));let latest=saved.runs.at(-1);for(const side of ['POS','NEG']){const t=JSON.parse(await fs.readFile(path.join(p.path,'runs',latest.id,'tables',side+'_Y_IS_opt.json')));assert.equal(t.rows.find(x=>x.IS_ID==='IS_002').Selected_Adduct,'+Na');assert.equal(t.rows.find(x=>x.IS_ID==='IS_002').Selection_Source,'manual')}
await page.reload();await page.waitForSelector('.lf-workflow-card:not(:disabled)',{timeout:120000});await page.getByRole('button',{name:'Recent projects',exact:true}).click();await page.getByRole('button',{name:/Interactive validation/}).click();await expect(page.locator('.lf-detail-title')).toContainText('Manually confirmed');await page.getByRole('button',{name:'Restore automatic selection'}).click();await expect(page.locator('.lf-detail-title')).toContainText('Automatic',{timeout:120000});saved=JSON.parse(await fs.readFile(path.join(p.path,'project.json')));latest=saved.runs.at(-1);const t=JSON.parse(await fs.readFile(path.join(p.path,'runs',latest.id,'tables/POS_Y_IS_opt.json')));assert.equal(t.rows.find(x=>x.IS_ID==='IS_001').Selection_Source,'auto');assert.equal(t.rows.find(x=>x.IS_ID==='IS_002').Selection_Source,'manual');console.log('PASS sorting, traces, filters, hover, zoom, manual selection, polarity preservation, reopen and restore. '+base);
}finally{await app.close()}})().catch(e=>{console.error(e);process.exitCode=1});
