const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');const {exportSelected}=require('../electron/selected-export.cjs');
test('download uses saved manual selection and all samples; preserves earlier downloads',async()=>{
 const projectPath=await fs.mkdtemp(path.join(os.tmpdir(),'lipidflow-export-'));try{
 const runDir=path.join(projectPath,'runs','test');await fs.mkdir(path.join(runDir,'tables'),{recursive:true});const row={IS_ID:'IS_001',IS_Name:'Standard <test>',Selected_Adduct:'+Na',Selection_Source:'manual',Target_mz:123,Measured_RT:2};
 await fs.writeFile(path.join(runDir,'tables/POS_Y_IS_opt.json'),JSON.stringify({rows:[row]}));await fs.writeFile(path.join(runDir,'tables/POS_Y_IS_opt.csv'),'saved final table\n');await fs.writeFile(path.join(runDir,'POS_eic.json'),JSON.stringify(['QC','Sample'].flatMap(Sample=>['+H','+Na'].map(adduct=>({IS_ID:row.IS_ID,adduct,Sample,rt:[1,2,3],intensity:[0,20,0]})))));
 const run={id:'test',status:'completed',result:{kind:'extraction',sides:['pos'],tables:[{name:'POS Y_IS_opt',file:'POS_Y_IS_opt'}]}};
 const a=await exportSelected({projectPath,runDir,run,side:'pos'}),b=await exportSelected({projectPath,runDir,run,side:'pos'});assert.notEqual(a.path,b.path);assert.deepEqual(a.missing,[]);assert.equal(await fs.readFile(path.join(a.path,'POS_Y_IS_opt.csv'),'utf8'),'saved final table\n');const manifest=JSON.parse(await fs.readFile(path.join(a.path,'manifest.json')));assert.equal(manifest.standards[0].adduct,'+Na');assert.deepEqual(manifest.standards[0].samples,['QC','Sample']);const trace=await fs.readFile(path.join(a.path,manifest.standards[0].csv),'utf8');assert(!trace.includes('+H'));assert(trace.includes('+Na'));const svg=await fs.readFile(path.join(a.path,manifest.standards[0].svg),'utf8');assert(svg.includes('&lt;test&gt;'));assert(svg.includes('manual'));
 await fs.unlink(path.join(runDir,'POS_eic.json'));const missing=await exportSelected({projectPath,runDir,run,side:'pos'});assert.deepEqual(missing.missing,['IS_001']);await assert.rejects(exportSelected({projectPath,runDir,run,side:'neg'}),/polarity/);
 }finally{await fs.rm(projectPath,{recursive:true,force:true})}
});
