import React,{useState} from 'react';
import {Download,FolderOpen} from 'lucide-react';
type Row=Record<string,any>;
export function DownloadResults({project,locked,api,onBusy}:{project:Row;locked:boolean;api:(a:string,p?:any)=>Promise<any>;onBusy:(v:boolean)=>void}){
 const run=[...project.runs].reverse().find((r:Row)=>r.status==='completed'&&r.result?.kind==='extraction');
 const [side,setSide]=useState('pos'),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const polarity=run?.result.sides.includes(side)?side:run?.result.sides[0];
 const download=async()=>{setSaving(true);onBusy(true);setError('');setNotice('');try{const r=await api('downloadSelected',{runId:run.id,side:polarity});setNotice(`Saved final table and ${r.count} peak-shape figures to ${r.path}${r.missing.length?'. Missing traces: '+r.missing.join(', '):''}`)}catch(e){setError((e as Error).message)}finally{setSaving(false);onBusy(false)}};
 return <div className="lf-download-page"><div className="eyebrow">INTERNAL STANDARD EXPLORATION</div><h1>Download results</h1><p className="lf-lead">Save your final internal-standard selections and peak shapes to this project.</p>{!run?<div className="lf-empty-projects">Complete internal standard exploration to download results.</div>:<section className="lf-download-card"><h2>Final selections & peak shapes</h2><p className="muted">Uses the latest completed result, including confirmed adduct selections.</p><p className="muted">Result saved: {new Date(run.finished||run.started).toLocaleString()}</p><label className="field"><span>Polarity</span><select aria-label="Download polarity" disabled={locked||saving} value={polarity} onChange={e=>{setSide(e.target.value);setNotice('')}}>{run.result.sides.map((s:string)=><option key={s} value={s}>{s.toUpperCase()}</option>)}</select></label><ul><li>Final internal-standard table · CSV</li><li>One selected-adduct peak-shape figure per internal standard · SVG</li><li>All available samples and original trace data · CSV</li><li>Browsable peak-shape gallery · HTML</li></ul><div className="lf-download-destination"><FolderOpen size={18}/><div><strong>Save to project folder</strong><p>{project.path}/exports/</p></div></div><button className="button" disabled={locked||saving} onClick={()=>download()}><Download size={17}/>{saving?'Saving…':'Download selected results'}</button><p className="muted">A new folder is created for each download and opens in your file browser.</p></section>}{notice&&<p className="lf-download-notice" role="status">{notice}</p>}{error&&<p className="lf-review-error" role="alert">{error}</p>}</div>
}
